import 'bootstrap-icons/font/bootstrap-icons.css';
import Title from "./components/Title";
import "./globals.css";

export const metadata = {
  title: "AnimeCom",
  description: "Generated by create next app",
};


export default function RootLayout({ children }) {
  return (
    <html lang="pt-br">
 
      <body>
        <div>
        <Title />
        {children}
        </div>
      
      </body>
      </html>
  );
}
